# Generated by Django 2.0.4 on 2018-04-29 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=20)),
                ('project_summary', models.CharField(max_length=1000)),
                ('project_pub', models.DateTimeField(verbose_name='date created')),
                ('project_members', models.ManyToManyField(to='user.User')),
                ('project_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to='user.User')),
            ],
            options={
                'ordering': ('-project_pub',),
            },
        ),
    ]
