# Generated by Django 2.0.4 on 2018-04-28 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_pub', models.DateTimeField(verbose_name='date published')),
                ('post_title', models.CharField(max_length=50)),
                ('post_content', models.TextField(max_length=1000)),
            ],
            options={
                'ordering': ('-post_pub',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_about', models.TextField(max_length=1000)),
                ('user_github_token', models.CharField(max_length=1000)),
            ],
            options={
                'ordering': ('user_name',),
            },
        ),
        migrations.AddField(
            model_name='post',
            name='post_interested',
            field=models.ManyToManyField(to='user.User'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_posts', to='user.User'),
        ),
    ]
