# Generated by Django 2.0.4 on 2018-04-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_email', models.CharField(max_length=20)),
                ('user_about', models.TextField(max_length=1000)),
                ('user_github_key', models.CharField(max_length=1000)),
            ],
        ),
    ]
